### ISSUE TITLE
NuGet\Install-Package EdjCase.ICP.InternetIdentity -Version 3.1.4  error

### ISSUE THREAD

**Issue by Intekai** [BoomDAO/ICP.NET#85]
when i install NuGet\Install-Package EdjCase.ICP.InternetIdentity -Version 3.1.4

error Fido2Net id not found

**Comment by Gekctek** [comment]
InternetIdentity is super experimental and I was considering removing it entirely. 
What is your use case for this? because there might be better ways than this library

**Comment by Intekai** [comment]
Hello, thanks for your reply.
I want login on ICP and retrice Identity ID

**Comment by Intekai** [comment]
retrive sorry

**Comment by Gekctek** [comment]
The consensus these days seems to be integrating with NFID/Internet Identity browser apps vs using the InternetIdentity package. @tommygames might be a good resource for that since im focused more on the backend

Im going to remove the InternetIdentity package due to security issues and lack of use and support
